-- ============================================================================
-- V1__initial_schema.sql
-- Flyway migration: Creates the complete parking lot management database schema.
-- Tables: users, parking_lots, parking_spots, vehicles, reservations, payments
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50),
    email         VARCHAR(120) NOT NULL UNIQUE,
    password      VARCHAR(255) NOT NULL,
    full_name     VARCHAR(100) NOT NULL,
    phone_number  VARCHAR(30),
    role          VARCHAR(20)  NOT NULL DEFAULT 'CUSTOMER',
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_user_email ON users (email);
CREATE INDEX idx_user_role ON users (role);

-- ---------------------------------------------------------------------------
-- 2. parking_lots
-- ---------------------------------------------------------------------------
CREATE TABLE parking_lots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)   NOT NULL,
    location    VARCHAR(255)   NOT NULL,
    capacity    INT            NOT NULL,
    hourly_rate NUMERIC(10, 2),
    is_active   BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_parking_lot_name     ON parking_lots (name);
CREATE INDEX idx_parking_lot_location ON parking_lots (location);

-- ---------------------------------------------------------------------------
-- 3. parking_spots
-- ---------------------------------------------------------------------------
CREATE TABLE parking_spots (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spot_number    VARCHAR(20)    NOT NULL,
    floor_number   INT            NOT NULL DEFAULT 1,
    spot_type      VARCHAR(20)    NOT NULL DEFAULT 'CAR',
    status         VARCHAR(20)    NOT NULL DEFAULT 'AVAILABLE',
    hourly_rate    NUMERIC(10, 2),
    parking_lot_id BIGINT         NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_spot_parking_lot FOREIGN KEY (parking_lot_id)
        REFERENCES parking_lots (id),
    CONSTRAINT uk_spot_lot_number UNIQUE (parking_lot_id, spot_number)
);

CREATE INDEX idx_spot_lot_status ON parking_spots (parking_lot_id, status);
CREATE INDEX idx_spot_type       ON parking_spots (spot_type);

-- ---------------------------------------------------------------------------
-- 4. vehicles
-- ---------------------------------------------------------------------------
CREATE TABLE vehicles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_plate VARCHAR(20)  NOT NULL UNIQUE,
    vehicle_type  VARCHAR(20)  NOT NULL,
    make          VARCHAR(50),
    model         VARCHAR(50),
    color         VARCHAR(30),
    user_id       BIGINT       NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_vehicle_user FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE UNIQUE INDEX idx_vehicle_license_plate ON vehicles (license_plate);
CREATE INDEX idx_vehicle_user_id              ON vehicles (user_id);

-- ---------------------------------------------------------------------------
-- 5. reservations
-- ---------------------------------------------------------------------------
CREATE TABLE reservations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT         NOT NULL,
    vehicle_id       BIGINT         NOT NULL,
    parking_spot_id  BIGINT         NOT NULL,
    start_time       TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time         TIMESTAMP WITH TIME ZONE NOT NULL,
    actual_entry_time TIMESTAMP WITH TIME ZONE,
    actual_exit_time  TIMESTAMP WITH TIME ZONE,
    total_amount     NUMERIC(10, 2) NOT NULL,
    status           VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_res_user    FOREIGN KEY (user_id)         REFERENCES users (id),
    CONSTRAINT fk_res_vehicle FOREIGN KEY (vehicle_id)      REFERENCES vehicles (id),
    CONSTRAINT fk_res_spot    FOREIGN KEY (parking_spot_id) REFERENCES parking_spots (id)
);

CREATE INDEX idx_res_spot_time ON reservations (parking_spot_id, start_time, end_time);
CREATE INDEX idx_res_user      ON reservations (user_id);
CREATE INDEX idx_res_status    ON reservations (status);

-- ---------------------------------------------------------------------------
-- 6. payments
-- ---------------------------------------------------------------------------
CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  BIGINT         NOT NULL UNIQUE,
    amount          NUMERIC(10, 2) NOT NULL,
    payment_method  VARCHAR(30)    NOT NULL,
    status          VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    currency        VARCHAR(3)     DEFAULT 'USD',
    transaction_id  VARCHAR(100)   UNIQUE,
    paid_at         TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_reservation FOREIGN KEY (reservation_id)
        REFERENCES reservations (id)
);

CREATE INDEX idx_payment_reservation ON payments (reservation_id);
CREATE UNIQUE INDEX idx_payment_tx_id ON payments (transaction_id);

-- ---------------------------------------------------------------------------
-- 7. report_metadata
-- ---------------------------------------------------------------------------
CREATE TABLE report_metadata (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type     VARCHAR(50)    NOT NULL,
    format          VARCHAR(20)    NOT NULL,
    status          VARCHAR(30)    NOT NULL DEFAULT 'generated',
    start_date      VARCHAR(50),
    end_date        VARCHAR(50),
    file_name       VARCHAR(255)   NOT NULL,
    content_type    VARCHAR(100)   NOT NULL,
    download_link   VARCHAR(255),
    requested_by    VARCHAR(120),
    content         BYTEA          NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_report_type         ON report_metadata (report_type);
CREATE INDEX idx_report_status       ON report_metadata (status);
CREATE INDEX idx_report_requested_by ON report_metadata (requested_by);
