-- ============================================================================
-- V2__create_feedback_table.sql
-- Flyway migration: Stores feedback users submit about the application or service.
-- ============================================================================

CREATE TABLE feedback (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT        NOT NULL,
    feedback_text  VARCHAR(1000) NOT NULL,
    rating         INTEGER       NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_feedback_user   FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_feedback_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_feedback_user_id ON feedback (user_id);
